### PR TITLE
#11 - Download UGNT from DCS

### PR DESCRIPTION
**Pull request by richmahn**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-box3/greek-apparatus-app/39)

### CODE REVIEW

**Comment by mannycolon** [comment]
Great work @richmahn, I was looking at the nextjs docs and realized they suggest the following.
```
if you're using Next.js 9.3 or newer, we recommend that you use getStaticProps or getServerSideProps instead of getInitialProps.
```
https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

**Comment by mannycolon** [comment]
Should we use getStaticProps instead?
https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

**Comment by richmahn** [comment]
@mannycolon Sounds good to me. Will change.

**Review by ancientTexts-net — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-box3/greek-apparatus-app/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @richmahn)

**Pull request merged**
